jobs:
  include:
    - stage: "Test"
      name: "Use custom image 2305-image3"
      vm:
        use:
          name: 03-org-images-t3

    - stage: "Test"
      name: "Use custom image 2305-image4"
      vm:
        use:
          name: 03-org-images-t4
